import { Employee, IEmployee } from 'src/app/shared/models/employee';

export const employees: IEmployee[] = [
  {
    firstName: 'Albert',
    middleName: null,
    lastName: 'Rau',
    age: 42,
    dob: '2001-01-01T00:00:00',
    hireDate: '2022-01-01T00:00:00',
    sex: 'M',
    address1: null,
    address2: null,
    city: 'null',
    state: 'null',
    zipCode: 'null',
    country: 'India',
    contactNo: '252236262',
    basic: 50000,
    taPercentage: 10,
    daPercentage: 10,
    hraPercentage: 10,
    salary: 0,
    imageUrl:
      'http://localhost:5293/images/employees/4c4e61c0-c5f8-4d73-80ef-415fbe050147_Albert_Rau.jpg',
    imageFile: null,
    description: 'Good Employee',
    departmentId: 8,
    designationId: 12,
    employeeTypeId: 3,
    departmentName: 'Support',
    designationName: 'Support Manager',
    employeeTypeName: 'Permanent',
    removeImage: false,
    id: 98,
  },
  {
    firstName: 'Amaya',
    middleName: null,
    lastName: 'Pacocha',
    age: 49,
    dob: '2001-01-01T00:00:00',
    hireDate: '2022-12-16T18:58:18.55',
    sex: 'M',
    address1: null,
    address2: null,
    city: null,
    state: null,
    zipCode: null,
    country: 'India',
    contactNo: null,
    basic: 0,
    taPercentage: 0,
    daPercentage: 0,
    hraPercentage: 0,
    salary: 0,
    imageUrl:
      'http://localhost:5293/images/employees/4050a256-368e-4950-9eea-d8b7f48eeb97_Amaya_Pacocha.jpg',
    imageFile: null,
    description: null,
    departmentId: 5,
    designationId: 10,
    employeeTypeId: 3,
    departmentName: 'HR',
    designationName: 'HR Manager',
    employeeTypeName: 'Permanent',
    removeImage: false,
    id: 59,
  },
  {
    firstName: 'Angelina',
    middleName: null,
    lastName: 'Russel',
    age: 14,
    dob: '0001-01-01T00:00:00',
    hireDate: '2022-12-16T18:58:18.55',
    sex: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    zipCode: null,
    country: null,
    contactNo: null,
    basic: 0,
    taPercentage: 0,
    daPercentage: 0,
    hraPercentage: 0,
    salary: 0,
    imageUrl: 'http://localhost:5293/images/employees/no-image.png',
    imageFile: null,
    description: null,
    departmentId: 7,
    designationId: 7,
    employeeTypeId: 4,
    departmentName: 'Development',
    designationName: 'Developer',
    employeeTypeName: 'Contract',
    removeImage: false,
    id: 73,
  },
  {
    firstName: 'Bertrand',
    middleName: null,
    lastName: 'Olson',
    age: 44,
    dob: '0001-01-01T00:00:00',
    hireDate: '2022-12-16T18:58:18.55',
    sex: 'M',
    address1: null,
    address2: null,
    city: null,
    state: null,
    zipCode: null,
    country: null,
    contactNo: null,
    basic: 0,
    taPercentage: 0,
    daPercentage: 0,
    hraPercentage: 0,
    salary: 0,
    imageUrl: 'http://localhost:5293/images/employees/no-image.png',
    imageFile: null,
    description: 'Nice Employee to work with',
    departmentId: 7,
    designationId: 8,
    employeeTypeId: 3,
    departmentName: 'Development',
    designationName: 'Senior Developer',
    employeeTypeName: 'Permanent',
    removeImage: false,
    id: 86,
  },
  {
    firstName: 'Bradly',
    middleName: null,
    lastName: 'Koepp',
    age: 11,
    dob: '0001-01-01T00:00:00',
    hireDate: '2022-12-16T18:58:18.5933333',
    sex: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    zipCode: null,
    country: null,
    contactNo: null,
    basic: 0,
    taPercentage: 0,
    daPercentage: 0,
    hraPercentage: 0,
    salary: 0,
    imageUrl: 'http://localhost:5293/images/employees/no-image.png',
    imageFile: null,
    description: null,
    departmentId: 8,
    designationId: 12,
    employeeTypeId: 4,
    departmentName: 'Support',
    designationName: 'Support Manager',
    employeeTypeName: 'Contract',
    removeImage: false,
    id: 96,
  },
  {
    firstName: 'Caesar',
    middleName: null,
    lastName: 'Abshire',
    age: 70,
    dob: '0001-01-01T00:00:00',
    hireDate: '2022-12-16T18:58:18.55',
    sex: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    zipCode: null,
    country: null,
    contactNo: null,
    basic: 0,
    taPercentage: 0,
    daPercentage: 0,
    hraPercentage: 0,
    salary: 0,
    imageUrl: 'http://localhost:5293/images/employees/no-image.png',
    imageFile: null,
    description: null,
    departmentId: 5,
    designationId: 10,
    employeeTypeId: 3,
    departmentName: 'HR',
    designationName: 'HR Manager',
    employeeTypeName: 'Permanent',
    removeImage: false,
    id: 55,
  },
];

export const firstPageEmployees = () => {
  return employees.slice(0, 3);
};
export function secondPageEmployees() {
  return employees.slice(3, 6);
}
